# NumPy的ndarray: 一种多维数组对象

## 创建ndarray

### array 函数创建

In [1]:
import numpy as np

In [4]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

### 嵌套序列

In [8]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

In [11]:
print(arr1.dtype,arr2.dtype)

float64 int32


### 其它函数

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
np.empty((2,3,2))

array([[[1.46268009e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.33511969e-306, 2.31746027e-052]],

       [[9.28204515e-072, 1.86454635e+160],
        [1.60399042e-051, 1.85586081e-051],
        [6.52077860e-038, 4.27632616e-033]]])

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## ndarray的数据类型

### dtype

In [17]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1.dtype,arr2.dtype)

float64 int32


### astype

In [3]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

float_arr = arr.astype(np.float32)
print(float_arr.dtype)

int32
float32


## 数组和标量之间的运算

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [7]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

## 基本的索引和切片

In [11]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[5]

5

In [13]:
arr[5:8]

array([5, 6, 7])

In [15]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [16]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [17]:
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [18]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr2d[2]

array([7, 8, 9])

In [20]:
arr2d[2][1]

8

In [21]:
arr2d[2,1]

8

## 切片索引

In [22]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [23]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])